CREATE DATABASE springdb;
use springdb;

CREATE TABLE PRODUTO(
ID BIGINT auto_increment primary KEY,
DESCRICAO VARCHAR(255),
PRECO DOUBLE
);

CREATE TABLE PEDIDO (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
DATA_PEDIDO DATE,
PRODUTO_ID BIGINT,
CONSTRAINT FK_PRODUTO_PEDIDO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);
